version: '3'
services:
  notebook:
    image: jupyter/datascience-notebook
    ports:
      - "7777:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./opt:/root/opt
    command: start-notebook.sh --NotebookApp.token=''    
  python3:
    restart: always
    build: .
    container_name: 'python3'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./opt:/root/opt